import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
// import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Roboto_Mono } from "next/font/google";

import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "sonner";

const geistSans = Inter({
  variable: "--font-Inter-sans",
  subsets: ["latin"],
});

const geistMono = Roboto_Mono({
  variable: "--font-Inter-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider >
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        <Toaster/>
        {children}
        </ThemeProvider>
      </body>
    </html>
    </TRPCReactProvider>
  );
}
